Neos:
  Flow:
    security:
      authentication:
        providers:
          DefaultProvider:
            provider: 'RFY\JWT\Security\Authentication\Provider\JsonWebAuthenticationProvider'
            token: 'RFY\JWT\Security\Authentication\Token\JsonWebToken'
            entryPoint: 'HttpBasic'
          JwtAuthenticationProvider:
            provider: 'RFY\JWT\Security\Authentication\Provider\JwtAuthenticationProvider'
            token: 'RFY\JWT\Security\Authentication\Token\JwtToken'

RFY:
  JWT:
    response:
      headers:
        'Access-Control-Allow-Origin': '*'
    key: ~
    algorithms:
      - HS256
    tokenSources:
      - from: header
        name: Authorization
    claimMapping: []
